import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:900}});
const page=await context.newPage();const errors=[],requests=[],badResponses=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));page.on('response',r=>{if(r.status()>=400)badResponses.push([r.url(),r.status()]);});
await page.goto('http://127.0.0.1:4173/navigator/');
await page.waitForFunction(()=>window.navigatorDiagnostics?.().ready,null,{timeout:20000});
await page.waitForTimeout(1000);
await fs.mkdir('test-results',{recursive:true});
await page.screenshot({path:'test-results/desktop.png'});
await page.keyboard.down('KeyW');await page.waitForTimeout(5000);
const moving=await page.evaluate(()=>window.navigatorDiagnostics());
await page.keyboard.up('KeyW');assert.ok(Math.hypot(moving.player.x,moving.player.y)>10);assert.equal(moving.metrics.drawCalls,3);
await page.locator('#reset').click();await page.waitForFunction(()=>!window.navigatorDiagnostics().busy);assert.equal((await page.evaluate(()=>window.navigatorDiagnostics())).player.x,0);
await page.mouse.move(600,400);await page.mouse.down();await page.mouse.move(750,400);await page.mouse.up();assert.ok((await page.evaluate(()=>window.navigatorDiagnostics())).player.heading>38);
await page.locator('#reset').click();await page.locator('#menu').click();assert.ok(await page.locator('#guide').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('#guide').isVisible(),false);
await page.locator('#stats-toggle').click();assert.ok(await page.locator('#stats').isVisible());await page.locator('#stats-toggle').click();
await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();try{await page.waitForFunction(()=>window.navigatorDiagnostics?.().ready,null,{timeout:12000});}catch(e){console.log(JSON.stringify({errors,badResponses,body:await page.locator('body').innerText(),diagnostics:await page.evaluate(()=>window.navigatorDiagnostics?.()),cache:await page.evaluate(async()=>Promise.all((await caches.keys()).map(async k=>[k,(await(await caches.open(k)).keys()).map(r=>r.url)])))}));throw e;}const offline=await page.evaluate(()=>window.navigatorDiagnostics());assert.ok(offline.ready);await context.setOffline(false);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png'});
await page.locator('[data-key="KeyW"]').hover();await page.mouse.down();await page.waitForTimeout(500);await page.mouse.up();assert.ok((await page.evaluate(()=>window.navigatorDiagnostics())).player.y>0);
await page.locator('#menu').click();await page.screenshot({path:'test-results/mobile-guide.png'});await page.locator('#close-guide').click();
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
await page.goto('http://127.0.0.1:4173/navigator/architecture.html');await page.screenshot({path:'test-results/architecture.png',fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(badResponses,[]);assert.ok(requests.every(url=>url.startsWith('http://127.0.0.1:4173/')));
const results={errors,badResponses,requests,moving,offline,viewport:{width:390,height:844},overflow};await fs.writeFile('test-results/browser-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
await browser.close();
